version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}testtask
    ports:
      - 8008:80
    build:
      context: .
      dockerfile: TestTask/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    links:
      - mongodb

  mongodb:
    container_name: mongo-dev
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: tasks
    volumes:
      - ./docker-entrypoint-initdb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro