version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}testtask
    ports:
      - 8008:80
    build:
      context: .
      dockerfile: TestTask/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    links:
      - mongodb

  mongodb:
    container_name: mongo-dev
    image: mongo
    ports:
      - '27017:27017'

volumes:
  mongodb_data:
    external: true