version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}testtask
    ports:
      - 8008:80
    build:
      context: .
      dockerfile: TestTask/Dockerfile

  mongodb:
    container_name: mongo-dev
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
  #mongo-express:
  #  container_name: mongo-express
  #  image: mongo-express
  #  restart: always
  #  depends_on:
  #    - mongodb
  #  environment:
  #    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #    - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
  #    - ME_CONFIG_MONGODB_SERVER=mongo-dev
  #    - ME_CONFIG_BASICAUTH_USERNAME=admin
  #    - ME_CONFIG_BASICAUTH_PASSWORD=ihavealongpassword
  #  ports:
  #    - '8081:8081'

volumes:
  mongodb_data:
    external: true